### ISSUE TITLE
Missing policy authorization context: user

### ISSUE THREAD

**Issue by jimmiejackson414** [kaka-ruto/graphql-on-rails-auth-docs#4]
Hello!

Wanted to thank you for creating such thorough docs on setting up GraphQL with Rails.

I've gone through the entire process and am trying to get GraphiQL working in my browser, but am receiving an error:
```
{
  "errors": [
    {
      "message": "Missing policy authorization context: user",
      "backtrace": [
        ...
      ]
   }
  ],
"data": {}
}
```
I'm pretty unfamiliar with Policies and it's been a few years since I last messed with Rails unfortunately. Do you know what could be the cause of this? Google hasn't been turning up many results to help fix this.

Thanks again!

**Comment by kaka-ruto** [comment]
Hi @jimmiejackson414 , good to have an issue no. 1!

You are missing the user object, with which action policy with authorize against.

So first try to signup a new user or login an existing one, before performing a mutation/query that requires the user to be logged in.

**Comment by jimmiejackson414** [comment]
Makes sense! I'd actually already created a user and was just attempting to log that user in, which is when I received that error.

I also noticed some inconsistencies with naming between Show and Get in a few places. For example [here](https://auth.graphql-on-rails.com/show-user-interactor) the code is describing Get User functionality, however the name of the file is `show.rb`.  And one more [here](https://auth.graphql-on-rails.com/user-policy), I believe there is a typo under "The User Policy" section. Correct me if I'm wrong, but I believe the `touch` commands should read `touch app/policies/user_policy.rb && touch spec/policies/user_policy_spec.rb`?

I have a feeling that there's simply a typo I missed or a missing require or something that is causing my original issue. I've made a pass through where I copy and paste everything from the docs to make sure and changed out a few things specific to my project like the name of the _schema.rb file.

**Comment by jimmiejackson414** [comment]
Do you know if these changes fixed the original question I posted about? I'd actually moved on to try a different Rails/GraphQL tutorial but keep running into issues, and would love to give this one another shot!

**Comment by kaka-ruto** [comment]
It may solve it. If not, you can share some code and I'll have a look? For both the tests and implementation if it's ok

**Comment by jimmiejackson414** [comment]
Going through the full process again, here are some other issues I’ve found:

- [Here](https://auth.graphql-on-rails.com/user-model) we generate a migration for the User, which already has password_digest as a column on the table. The next step talks about needing to change the password column to password_digest, however that was already done on the previous step and running rails db:migrate on the Encrypting Passwords sections returns an error.
- The test for the [Create User Interactor](https://auth.graphql-on-rails.com/create-user-interactor) section is missing a single quote on the import.
- I get an error on the test for the [Show User Interactor](https://auth.graphql-on-rails.com/show-user-interactor) step: NameError: uninitialized constant Users::Show? I believe it’s because it’s missing a require 'rails_helper'. Same goes for the [Update User Interactor](https://auth.graphql-on-rails.com/update-user-interactor) and [Delete User Interactor](https://auth.graphql-on-rails.com/delete-user-interactor).
- On the [Mutations](https://auth.graphql-on-rails.com/mutations) step, I think you meant to name the files “app/graphql/mutations/users/create.rb” and “spec/graphql/mutations/users/create_spec.rb”, which are used on the very next step.
- After going through the full tutorial, I am now receiving the error “exception”: “#<NoMethodError: undefined method `flash=' for #<ActionDispatch::Request:0x00007fe37a454d58>>“, which has something to do with CSRF authenticity token?

**Comment by jimmiejackson414** [comment]
Hi @kaka-ruto I wanted to follow up here. Do you have a working repo I could take a look at for this setup? I managed to avoid the `Missing policy authorization context: user` error by adding `authorize :user, optional: true` to the application_policy, but that feels like a band-aid fix. I now receive `undefined method 'id' for nil:NilClass` coming from `app/policies/user_policy.rb:5:in `show?'` and then `app/policies/user_policy.rb:19:in `self?'`. I'm unsure of why it's attempting to perform a policy check on a create, and even more unsure of why it's hitting the show? method for a create. Thanks!

**Comment by kaka-ruto** [comment]
Hi @jimmiejackson414 , sorry I've been away, work's gotten hold of me lately. Here is a working repo of the project https://github.com/kaka-ruto/graphql-on-rails-auth

Once I get some time I will come address some of the issues you've faced, so feel free to populate this thread or the working repo's with quizzes

**Comment by jimmiejackson414** [comment]
No problem, totally understand! Thanks for the working repo, I'm looking forward to going through it. Should I go ahead and close this issue?
